### ISSUE TITLE
API error on 4 input<>output moves for Activity-related file

### ISSUE THREAD

**Issue by barrywark** [physion/ovation-webapi#157]
Take an entry from Input move it to Output and back again. On the 4th move between Input and Output it generates a 500 error from the API

**Comment by barrywark** [comment]
@dguettler can you fill in details?

**Comment by dguettler** [comment]
Not much to add to it. Take an entry from Input move it to Output and back again. On the 4th move between Input and Output it generates a 500 error from the API

**Comment by rensm** [comment]
Migrated to pivotal tracker https://www.pivotaltracker.com/story/show/120102431
