### ISSUE TITLE
Debug file revisions call

### ISSUE THREAD

**Issue by barrywark** [physion/ovation-webapi#160]

**Comment by barrywark** [comment]
Testing against https://app-staging.ovation.io/projects/9d81ab39-1dff-45e9-8892-2778e2c522f0/contents/files/5a98ab58-5106-42f3-9831-686afef7bd88/preview, a file with 3 revisions, https://api-dev.ovation.io/api/v1/files/5a98ab58-5106-42f3-9831-686afef7bd88/links/revisions returns 3 revisions (as expected). Note that https://api-dev.ovation.io/api/v1/files/5a98ab58-5106-42f3-9831-686afef7bd88/heads returns only the (single) HEAD revision.

**Comment by barrywark** [comment]
@rensm were you able to resolve this on the frontend, or do you need a webapi fix?

**Comment by rensm** [comment]
Hey Barry,

No, don't need a web API fix for this.  It was a serializer issue.

**Comment by barrywark** [comment]
:thumbsup:
