### ISSUE TITLE
validate email in team invite dialog

### ISSUE THREAD

**Issue by barrywark** [physion/ovation-webapi#192]

**Comment by barrywark** [comment]
AJAX Error: error POST unknown on Raygun traceable to this dialog passing an invalid email

**Comment by barrywark** [comment]
Issue moved to [physion/ovation-base #267](https://github.com/physion/ovation-base/issues/267) via [**ZenHub.io**](https://www.zenhub.io/)

**Comment by IntegerMan** [comment]
Random question here: What did the error wind up being? We run Raygun and got an AJAX Error: error POST unknown reported a few times and have no idea what this is even about. You were about the only Google hit for it and ovation-base #267 is not publicly visible.

**Comment by barrywark** [comment]
@IntegerMan we dever definitively tracked down the culprit. In our case, we get these "POST unknown" or "GET unknown" errors when our API returns a 401. It seems like a catch-all exception handler. Still trying to find the best solution in Ember.Data + Raygun. I hope that's a helpful lead!
